version: '2'

volumes:
  data: {}

services:
  steam:
    image: andrey01/steam
    network_mode: bridge
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/machine-id:/etc/machine-id:ro
      - $XDG_RUNTIME_DIR/pulse:/run/user/1000/pulse
      - /dev/shm:/dev/shm
      - data:/home
      # - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro
    devices:
      - /dev/nvidia0
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      # uncomment this when running NVIDIA Driver >= 361
      - /dev/nvidia-modeset
      - /dev/dri
      # - /dev/snd
    environment:
      - DISPLAY=unix$DISPLAY
      - PULSE_SERVER=unix:$XDG_RUNTIME_DIR/pulse/native
      # Use Steam provided runtime, requires --reset
      # Steam provided runtime seems to be less stable with this image
      # - STEAM_RUNTIME=1
